### PR TITLE
[FEATURE] Enable auto install via composer

### PR DESCRIPTION
**Pull request by borishinzer**
* As it should be easier to use the standard we use auto installation as
  phpcs standard via composer

### CODE REVIEW

**Comment by web-vision** [comment]
By providing the requirement to Code Sniffer it get installed and you can use the standard out of the box without installing Code Sniffer seperatly.

In addition the type provided installation as Standard out of the box, so no further configuration. Just use ```--standard=Ecg```

**Comment by DanielSiepmann** [comment]
By providing the requirement to Code Sniffer it get installed and you can use the standard out of the box without installing Code Sniffer seperatly.

In addition the type provided installation as Standard out of the box, so no further configuration. Just use ```--standard=Ecg```.

**Comment by DanielSiepmann** [comment]
Can you at least provide feedback why you won't merge this change @zlik ?

**Comment by zlik** [comment]
Sure, sorry about that. You can install PHPCS globally only once (`composer global require "squizlabs/php_codesniffer=*"`) and then use it with multiple standards without installing PHPCS for each one.

**Pull request closed without merging**
