### PR TITLE
Add PHP_Codesniffer to require

### PR DESCRIPTION
**Pull request by davidwindell**

### CODE REVIEW

**Comment by davidwindell** [comment]
We use fresh Docker images per project so we wouldn't install it globally.

If you have global required it, won't composer detect this and not install on the project level?

**Comment by zlik** [comment]
@davidwindell, I apologize I had to revert the pull request because PHPCS will actually be installed on the project level even when installed globally. You can a command to install PHPCS globally to your provisioning script. I updated README with the recommended installation method.

**Comment by zlik** [comment]
@davidwindell,
Note: Alternatively to installing PHP_CodeSniffer globally, you can include dependencies for both `magento-ecg/coding-standard` and `squizlabs/php_codesniffer` in your composer.json file. For example:
```
{
    "require": {
        "magento-ecg/coding-standard": ">=3.0",
        "squizlabs/php_codesniffer": "3.*"
    }
}
```

**Comment by davidwindell** [comment]
Yep, that's what we've been doing but the usual practice is to require all dependencies at the vendor level.

**Pull request merged**
